/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net;

import java.io.BufferedReader;
import java.io.FileReader;
import java.net.Inet4Address;
import java.net.InetAddress;

/**
 *
 * @author tuanv
 */
public class FrmServer extends javax.swing.JFrame {

    GuiNhan gn = new GuiNhan();

    /**
     * Creates new form FrmServer
     */
    long s = -1;

    long tohop(int n, int k) {
        if (n == k || n == 0) {
            return 1;
        }
        return tohop(n - 1, k) + tohop(n - 1, k - 1);
    }

    public class Tuyendoan extends Thread {

        int n, k;
        String ip;

        public Tuyendoan(int n, int k, String ip) {
            this.n = n;
            this.k = k;
            this.ip = ip;
        }

        public void run() {
            try {
                s = tohop(n, k);
                gn.Gui(String.valueOf(s), ip, 1261);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public class TuyenNhan extends Thread {

        public void run() {
            while (true) {
                try {
                    Runtime r = Runtime.getRuntime();
                    String msg = gn.Nhan();
                    String[] split = msg.split(":");
                    if (split[1].equals("/tm")) {
                        gn.Gui("ltpt", split[0], 1261);
                    }
                    if (split[1].equals("/ht")) {
                        gn.Gui(InetAddress.getLocalHost().getHostName(), split[0], 1261);
                    }
                    if(split[1].startsWith("/+")){
                        long sum = 0,min =0,max=0,sochuso=0;
                        String[] input = split[1].split(";");
                        for(int i = 1; i < input.length; i++){
                            try{
                                long tam = Long.parseLong(input[i]);
                                if(i==1){
                                    min = tam;
                                    max = tam;
                                }else{
                                    if(min >tam ) min=tam;
                                    if(max < tam) max=tam;
                                }
                                sum+=tam;
                                sochuso++;
                            }catch(Exception e){
                                e.printStackTrace();
                            }
                        }
                        gn.Gui("Tong: "+sum, split[0], 1261);
                        gn.Gui("So lon nhat: "+max, split[0], 1261);
                        gn.Gui("So nho nhat: "+min, split[0], 1261);
                        gn.Gui("So chu so Client gui len: "+sochuso, split[0], 1261);
                    }
                    if(split[1].equals("/excel")){
                        r.exec("C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE");
                    }
                    if(split[1].equals("/notepad")){
                        r.exec("notepad");
                    }
                    if (split[1].equals("/xskt")) {
                        FileReader file = new FileReader("xskt.txt");
                        BufferedReader read = new BufferedReader(file);
                        while (true) {
                            String s = read.readLine();
                            if (s == null || s == "") {
                                break;
                            }
                            gn.Gui(s, split[0], 1261);
                        }
                    }
                    if (split[1].equals("/quit")) {
                        r.exec("shutdown");
                    }
                    if (split[1].startsWith("/C")) {
                        String[] tohop = split[1].split("[;]");
                        int k = Integer.parseInt(tohop[1]);
                        int n = Integer.parseInt(tohop[2]);
                        Tuyendoan tuyendoan = new Tuyendoan(n, k,split[0]);
                        tuyendoan.start();

                    }
                    list1.add(msg);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }

    public FrmServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        ipTxt = new javax.swing.JTextField();
        portTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dataTxt = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("IP");

        jLabel2.setText("Port");

        dataTxt.setText("jTextField3");

        sendBtn.setText("Send");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(ipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(portTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataTxt)
                        .addGap(18, 18, 18)
                        .addComponent(sendBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(portTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendBtn)
                    .addComponent(dataTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {

            gn.MoCong(1260);
            TuyenNhan tn = new TuyenNhan();
            tn.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        // TODO add your handling code here:
        String ip = ipTxt.getText();
        String port = portTxt.getText();
        String data = dataTxt.getText();
        try {
            gn.Gui(data, ip, Integer.valueOf(port));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_sendBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dataTxt;
    private javax.swing.JTextField ipTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.List list1;
    private javax.swing.JTextField portTxt;
    private javax.swing.JButton sendBtn;
    // End of variables declaration//GEN-END:variables
}
